services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - backend
  

  stubpay:
    build: .
    container_name: todo-app
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Dspring.profiles.active=prod
    networks:
      - backend

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    networks:
      - backend

networks:
  backend: